"""phase2_risk_engine

Revision ID: 572f080f3daa
Revises: 864cf5488d33
Create Date: 2026-06-23 07:42:52.772198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '572f080f3daa'
down_revision: Union[str, None] = '864cf5488d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Every table below has tenant_id, so every one gets the RLS policy block
# mandated by spec §4 / §0.4. All are mutable (never hard-deleted) — no
# append-only tables in this set, unlike Phase 1's raw_files/raw_records.
_ALL_TENANT_TABLES = (
    "risk_configs",
    "risk_assessments",
    "risk_findings",
    "interventions",
    "intervention_outcomes",
    "risk_alerts",
    "faculty_scopes",
)


def _apply_rls(table_name: str) -> None:
    op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON {table_name}
          USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
          WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_scopes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_ref', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("scope_type IN ('department', 'programme', 'course', 'section')", name='ck_faculty_scopes_scope_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'scope_type', 'scope_ref', name='uq_faculty_scopes_natural_key')
    )
    op.create_index(op.f('ix_faculty_scopes_tenant_id'), 'faculty_scopes', ['tenant_id'], unique=False)
    op.create_table('risk_configs',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_configs_tenant_id'), 'risk_configs', ['tenant_id'], unique=False)
    op.create_index('uq_risk_configs_tenant_active', 'risk_configs', ['tenant_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('risk_assessments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('subject_minor_status', sa.String(), nullable=False),
    sa.Column('signals_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('triggered_by_import_batch_id', sa.UUID(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("model_type IN ('rules', 'ml')", name='ck_risk_assessments_model_type'),
    sa.CheckConstraint("subject_minor_status IN ('minor', 'adult', 'unknown')", name='ck_risk_assessments_minor_status'),
    sa.CheckConstraint("tier IN ('low', 'watch', 'high')", name='ck_risk_assessments_tier'),
    sa.CheckConstraint("triggered_by IN ('import', 'manual', 'scheduled')", name='ck_risk_assessments_triggered_by'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessments_tenant_current_score', 'risk_assessments', ['tenant_id', 'is_current', 'overall_score'], unique=False)
    op.create_index('ix_risk_assessments_tenant_current_tier', 'risk_assessments', ['tenant_id', 'is_current', 'tier'], unique=False)
    op.create_index(op.f('ix_risk_assessments_tenant_id'), 'risk_assessments', ['tenant_id'], unique=False)
    op.create_index('uq_risk_assessments_tenant_student_current', 'risk_assessments', ['tenant_id', 'student_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('interventions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('source_assessment_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('guardian_consent_confirmed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('suggested', 'open', 'in_progress', 'completed', 'dismissed')", name='ck_interventions_status'),
    sa.CheckConstraint("type IN ('mentor_meeting', 'remedial_class', 'parent_contact', 'counselling', 'other')", name='ck_interventions_type'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guardian_consent_confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interventions_tenant_assigned_status', 'interventions', ['tenant_id', 'assigned_to', 'status'], unique=False)
    op.create_index(op.f('ix_interventions_tenant_id'), 'interventions', ['tenant_id'], unique=False)
    op.create_index('ix_interventions_tenant_student_status', 'interventions', ['tenant_id', 'student_id', 'status'], unique=False)
    op.create_table('risk_alerts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(), server_default=sa.text("'in_app'"), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("channel IN ('in_app', 'email')", name='ck_risk_alerts_channel'),
    sa.CheckConstraint("status IN ('pending', 'sent', 'read', 'suppressed')", name='ck_risk_alerts_status'),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alerts_tenant_id'), 'risk_alerts', ['tenant_id'], unique=False)
    op.create_index('ix_risk_alerts_tenant_recipient_status', 'risk_alerts', ['tenant_id', 'recipient_user_id', 'status'], unique=False)
    op.create_table('risk_findings',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('weight_contribution', sa.Float(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("risk_type IN ('attendance', 'academic', 'fee')", name='ck_risk_findings_risk_type'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name='ck_risk_findings_severity'),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_findings_tenant_assessment', 'risk_findings', ['tenant_id', 'assessment_id'], unique=False)
    op.create_index(op.f('ix_risk_findings_tenant_id'), 'risk_findings', ['tenant_id'], unique=False)
    op.create_index('ix_risk_findings_tenant_risk_type', 'risk_findings', ['tenant_id', 'risk_type'], unique=False)
    op.create_table('intervention_outcomes',
    sa.Column('intervention_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("outcome IN ('improved', 'no_change', 'worsened', 'unknown')", name='ck_intervention_outcomes_outcome'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_outcomes_tenant_id'), 'intervention_outcomes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table_name in _ALL_TENANT_TABLES:
        _apply_rls(table_name)

    for table_name in _ALL_TENANT_TABLES:
        op.execute(f"GRANT SELECT, INSERT, UPDATE ON {table_name} TO app_user")


def downgrade() -> None:
    op.execute(f"REVOKE ALL ON {', '.join(_ALL_TENANT_TABLES)} FROM app_user")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intervention_outcomes_tenant_id'), table_name='intervention_outcomes')
    op.drop_table('intervention_outcomes')
    op.drop_index('ix_risk_findings_tenant_risk_type', table_name='risk_findings')
    op.drop_index(op.f('ix_risk_findings_tenant_id'), table_name='risk_findings')
    op.drop_index('ix_risk_findings_tenant_assessment', table_name='risk_findings')
    op.drop_table('risk_findings')
    op.drop_index('ix_risk_alerts_tenant_recipient_status', table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_tenant_id'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index('ix_interventions_tenant_student_status', table_name='interventions')
    op.drop_index(op.f('ix_interventions_tenant_id'), table_name='interventions')
    op.drop_index('ix_interventions_tenant_assigned_status', table_name='interventions')
    op.drop_table('interventions')
    op.drop_index('uq_risk_assessments_tenant_student_current', table_name='risk_assessments', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_risk_assessments_tenant_id'), table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_tenant_current_tier', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_tenant_current_score', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('uq_risk_configs_tenant_active', table_name='risk_configs', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_risk_configs_tenant_id'), table_name='risk_configs')
    op.drop_table('risk_configs')
    op.drop_index(op.f('ix_faculty_scopes_tenant_id'), table_name='faculty_scopes')
    op.drop_table('faculty_scopes')
    # ### end Alembic commands ###
