"""phase2_hardening_assessment_date_recompute_status

Revision ID: 6bf2927b6b7a
Revises: 572f080f3daa
Create Date: 2026-06-23 16:24:08.534380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bf2927b6b7a'
down_revision: Union[str, None] = '572f080f3daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batches', sa.Column('risk_recompute_status', sa.String(), nullable=True))
    op.add_column('import_batches', sa.Column('risk_recompute_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('internal_marks', sa.Column('assessment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###

    # Not autogenerated: Alembic's default comparator doesn't detect CHECK
    # constraint additions on existing tables (spec change order CHANGE 3a).
    op.create_check_constraint(
        "ck_import_batches_risk_recompute_status",
        "import_batches",
        "risk_recompute_status IS NULL OR risk_recompute_status IN ('ok', 'partial', 'failed', 'skipped')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_import_batches_risk_recompute_status", "import_batches", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internal_marks', 'assessment_date')
    op.drop_column('import_batches', 'risk_recompute_summary')
    op.drop_column('import_batches', 'risk_recompute_status')
    # ### end Alembic commands ###
