"""phase0 foundation: tenants users audit_log

Revision ID: 7c901e329671
Revises:
Create Date: 2026-06-22 09:44:23.090460

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c901e329671'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Tables with tenant_id get the RLS policy block mandated by spec §4.3.
_RLS_TABLES = ("users", "audit_log")


def _apply_rls(table_name: str) -> None:
    op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON {table_name}
          USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
          WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
        """
    )


def _bootstrap_app_user() -> None:
    """Create (or repassword) the non-superuser app_user role the running app
    connects as (spec §4.3). Password is read from env at migration time —
    never hardcoded — and escaped for safe literal embedding; CREATE/ALTER ROLE
    are utility statements that Postgres does not accept bind parameters for."""
    bind = op.get_bind()
    password = os.environ["APP_DB_PASSWORD"]
    escaped_password = password.replace("'", "''")

    role_exists = bind.execute(sa.text("SELECT 1 FROM pg_roles WHERE rolname = 'app_user'")).scalar()
    if role_exists:
        op.execute(f"ALTER ROLE app_user WITH LOGIN PASSWORD '{escaped_password}'")
    else:
        op.execute(f"CREATE ROLE app_user WITH LOGIN PASSWORD '{escaped_password}'")

    op.execute(
        """
        DO $$
        BEGIN
            EXECUTE format('GRANT CONNECT ON DATABASE %I TO app_user', current_database());
        END
        $$
        """
    )
    op.execute("GRANT USAGE ON SCHEMA public TO app_user")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_log',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("action IN ('insert', 'update', 'soft_delete')", name='ck_audit_log_action'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'principal', 'registrar', 'iqac', 'faculty', 'student')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table_name in _RLS_TABLES:
        _apply_rls(table_name)

    _bootstrap_app_user()
    op.execute("GRANT SELECT, INSERT, UPDATE ON tenants TO app_user")
    op.execute("GRANT SELECT, INSERT, UPDATE ON users TO app_user")
    op.execute("GRANT SELECT, INSERT ON audit_log TO app_user")  # append-only: no UPDATE/DELETE


def downgrade() -> None:
    op.execute("REVOKE ALL ON tenants, users, audit_log FROM app_user")
    op.execute("REVOKE USAGE ON SCHEMA public FROM app_user")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('tenants')
    # ### end Alembic commands ###

    op.execute("DROP ROLE IF EXISTS app_user")
