"""phase1 ingestion: canonical, identity, conflict tables

Revision ID: 864cf5488d33
Revises: 7c901e329671
Create Date: 2026-06-22 11:57:06.277144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '864cf5488d33'
down_revision: Union[str, None] = '7c901e329671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Every table below has tenant_id, so every one gets the RLS policy block
# mandated by spec §4.3.
_ALL_TENANT_TABLES = (
    "departments",
    "hostel",
    "merge_review_items",
    "placement",
    "research_publication",
    "source_systems",
    "column_mappings",
    "entity_identity_map",
    "faculty",
    "import_batches",
    "programmes",
    "courses",
    "data_conflicts",
    "raw_files",
    "raw_records",
    "staging_records",
    "students",
    "attendance",
    "enrollment",
    "fees",
    "internal_marks",
    "semester_results",
)

# Append-only / immutable layer (spec §5.2): SELECT + INSERT only, never UPDATE.
_APPEND_ONLY_TABLES = ("raw_files", "raw_records")

# Everything else is mutable (status transitions, soft-delete via is_deleted,
# review workflows) but still never DELETE — no-hard-delete principle (§1).
_MUTABLE_TABLES = tuple(t for t in _ALL_TENANT_TABLES if t not in _APPEND_ONLY_TABLES)


def _apply_rls(table_name: str) -> None:
    op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON {table_name}
          USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
          WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_departments_tenant_code')
    )
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('hostel',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_tenant_id'), 'hostel', ['tenant_id'], unique=False)
    op.create_table('merge_review_items',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('candidate_canonical_id', sa.UUID(), nullable=False),
    sa.Column('incoming_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending_review'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('pending_review', 'confirmed', 'rejected')", name='ck_merge_review_items_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merge_review_items_tenant_id'), 'merge_review_items', ['tenant_id'], unique=False)
    op.create_table('placement',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_tenant_id'), 'placement', ['tenant_id'], unique=False)
    op.create_table('research_publication',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_publication_tenant_id'), 'research_publication', ['tenant_id'], unique=False)
    op.create_table('source_systems',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('precedence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_source_systems_tenant_name')
    )
    op.create_index(op.f('ix_source_systems_tenant_id'), 'source_systems', ['tenant_id'], unique=False)
    op.create_table('column_mappings',
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_mappings_tenant_id'), 'column_mappings', ['tenant_id'], unique=False)
    op.create_table('entity_identity_map',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=False),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("match_method IN ('deterministic', 'fuzzy', 'manual')", name='ck_identity_map_match_method'),
    sa.CheckConstraint("status IN ('auto_linked', 'pending_review', 'confirmed', 'rejected')", name='ck_identity_map_status'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'source_system_id', 'source_id', name='uq_identity_map_natural_key')
    )
    op.create_index(op.f('ix_entity_identity_map_tenant_id'), 'entity_identity_map', ['tenant_id'], unique=False)
    op.create_table('faculty',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'employee_code', name='uq_faculty_tenant_employee_code')
    )
    op.create_index(op.f('ix_faculty_tenant_id'), 'faculty', ['tenant_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'RECEIVED'"), nullable=False),
    sa.Column('row_count_raw', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('row_count_loaded', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('row_count_quarantined', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('reconciliation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('RECEIVED', 'PARSED', 'MAPPED', 'CLEANED', 'RESOLVED', 'LOADED', 'RECONCILED', 'COMPLETED', 'FAILED')", name='ck_import_batches_status'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_tenant_id'), 'import_batches', ['tenant_id'], unique=False)
    op.create_index('ix_import_batches_tenant_source_hash', 'import_batches', ['tenant_id', 'source_system_id', 'content_hash'], unique=False)
    op.create_table('programmes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_programmes_tenant_code')
    )
    op.create_index(op.f('ix_programmes_tenant_id'), 'programmes', ['tenant_id'], unique=False)
    op.create_table('courses',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_courses_tenant_code')
    )
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_table('data_conflicts',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('existing_value', sa.String(), nullable=True),
    sa.Column('incoming_value', sa.String(), nullable=True),
    sa.Column('existing_source', sa.UUID(), nullable=True),
    sa.Column('incoming_source', sa.UUID(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['existing_source'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['incoming_source'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_conflicts_tenant_id'), 'data_conflicts', ['tenant_id'], unique=False)
    op.create_table('raw_files',
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_files_tenant_id'), 'raw_files', ['tenant_id'], unique=False)
    op.create_table('raw_records',
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_records_import_batch_id', 'raw_records', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_raw_records_tenant_id'), 'raw_records', ['tenant_id'], unique=False)
    op.create_table('staging_records',
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('cleaned_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_entity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("validation_status IN ('valid', 'quarantined')", name='ck_staging_records_validation_status'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staging_records_import_batch_id', 'staging_records', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_staging_records_tenant_id'), 'staging_records', ['tenant_id'], unique=False)
    op.create_table('students',
    sa.Column('canonical_roll_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('admission_year', sa.Integer(), nullable=True),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canonical_roll_no', name='uq_students_tenant_roll_no')
    )
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.create_table('attendance',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('class_date', sa.Date(), nullable=False),
    sa.Column('session_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('present', 'absent', 'leave')", name='ck_attendance_status'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'student_id', 'course_id', 'class_date', 'session_no', name='uq_attendance_natural_key')
    )
    op.create_index(op.f('ix_attendance_tenant_id'), 'attendance', ['tenant_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'student_id', 'course_id', 'academic_year', name='uq_enrollment_natural_key')
    )
    op.create_index(op.f('ix_enrollment_tenant_id'), 'enrollment', ['tenant_id'], unique=False)
    op.create_table('fees',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('fee_head', sa.String(), nullable=False),
    sa.Column('amount_due', sa.Numeric(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'student_id', 'term', 'fee_head', name='uq_fees_natural_key')
    )
    op.create_index(op.f('ix_fees_tenant_id'), 'fees', ['tenant_id'], unique=False)
    op.create_table('internal_marks',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('assessment_type', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_marks', sa.Numeric(), nullable=False),
    sa.Column('obtained', sa.Numeric(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'student_id', 'course_id', 'assessment_type', 'attempt', name='uq_internal_marks_natural_key')
    )
    op.create_index(op.f('ix_internal_marks_tenant_id'), 'internal_marks', ['tenant_id'], unique=False)
    op.create_table('semester_results',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('result_status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'student_id', 'course_id', 'academic_year', 'semester', 'attempt', name='uq_semester_results_natural_key')
    )
    op.create_index(op.f('ix_semester_results_tenant_id'), 'semester_results', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table_name in _ALL_TENANT_TABLES:
        _apply_rls(table_name)

    for table_name in _APPEND_ONLY_TABLES:
        op.execute(f"GRANT SELECT, INSERT ON {table_name} TO app_user")

    for table_name in _MUTABLE_TABLES:
        op.execute(f"GRANT SELECT, INSERT, UPDATE ON {table_name} TO app_user")


def downgrade() -> None:
    op.execute(f"REVOKE ALL ON {', '.join(_ALL_TENANT_TABLES)} FROM app_user")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semester_results_tenant_id'), table_name='semester_results')
    op.drop_table('semester_results')
    op.drop_index(op.f('ix_internal_marks_tenant_id'), table_name='internal_marks')
    op.drop_table('internal_marks')
    op.drop_index(op.f('ix_fees_tenant_id'), table_name='fees')
    op.drop_table('fees')
    op.drop_index(op.f('ix_enrollment_tenant_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_attendance_tenant_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_staging_records_tenant_id'), table_name='staging_records')
    op.drop_index('ix_staging_records_import_batch_id', table_name='staging_records')
    op.drop_table('staging_records')
    op.drop_index(op.f('ix_raw_records_tenant_id'), table_name='raw_records')
    op.drop_index('ix_raw_records_import_batch_id', table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_raw_files_tenant_id'), table_name='raw_files')
    op.drop_table('raw_files')
    op.drop_index(op.f('ix_data_conflicts_tenant_id'), table_name='data_conflicts')
    op.drop_table('data_conflicts')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_programmes_tenant_id'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index('ix_import_batches_tenant_source_hash', table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_tenant_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_faculty_tenant_id'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_entity_identity_map_tenant_id'), table_name='entity_identity_map')
    op.drop_table('entity_identity_map')
    op.drop_index(op.f('ix_column_mappings_tenant_id'), table_name='column_mappings')
    op.drop_table('column_mappings')
    op.drop_index(op.f('ix_source_systems_tenant_id'), table_name='source_systems')
    op.drop_table('source_systems')
    op.drop_index(op.f('ix_research_publication_tenant_id'), table_name='research_publication')
    op.drop_table('research_publication')
    op.drop_index(op.f('ix_placement_tenant_id'), table_name='placement')
    op.drop_table('placement')
    op.drop_index(op.f('ix_merge_review_items_tenant_id'), table_name='merge_review_items')
    op.drop_table('merge_review_items')
    op.drop_index(op.f('ix_hostel_tenant_id'), table_name='hostel')
    op.drop_table('hostel')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
