"""phase2_hardening_part2_not_null_student_course

Revision ID: d67e374fb99f
Revises: 6bf2927b6b7a
Create Date: 2026-06-24 06:52:47.903524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67e374fb99f'
down_revision: Union[str, None] = '6bf2927b6b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fees', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('internal_marks', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('internal_marks', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('internal_marks', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('internal_marks', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fees', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
