import {
  Building2,
  Calendar,
  FileSpreadsheet,
  FileText,
  Globe,
  Hash,
  Info,
  Link,
  Lock,
  Printer,
  Sparkles,
  User,
} from "lucide-react";

import type {
  ArtifactMeta,
  ArtifactSection,
  CommentEntry,
  ExportOption,
  MetadataRow,
  VersionEntry,
  WorkflowStage,
} from "./types";

export const MOCK_ARTIFACT: ArtifactMeta = {
  id: "DR-1180",
  name: "Department performance report",
  type: "Department report",
  approver: "Academic Head",
  version: "v4",
  updated: "12 min ago",
  sensitivity: "Internal",
  owner: "Dr. Rao",
  department: "Computer Science",
};

export const MOCK_SECTIONS: ArtifactSection[] = [
  {
    id: "s1",
    title: "Executive summary",
    kind: "text",
    aiGenerated: true,
    markdown:
      "This artifact was generated by Forevue from the records you already keep, then refined by you. **Activity is steady overall**, with a small number of items that need attention before this can move to review. Every figure below is grounded in a named source.",
  },
  {
    id: "s2",
    title: "Key metrics",
    kind: "stats",
  },
  {
    id: "s3",
    title: "Breakdown",
    kind: "table",
  },
  {
    id: "s4",
    title: "Trend",
    kind: "chart",
  },
  {
    id: "s5",
    title: "Recommendations",
    kind: "text",
    aiGenerated: true,
    hasComment: true,
    hasErpAction: true,
    markdown:
      "Based on the evidence above, the recommended next step is a short, targeted intervention for the items flagged as needing attention. This section is advisory — review it, edit anything, and approve before it is shared or written back to the ERP.",
  },
];

export const MOCK_VERSIONS: VersionEntry[] = [
  {
    id: "v4",
    label: "v4",
    tag: "Human edited",
    tagTone: "human",
    who: "Dr. Rao",
    time: "12 min ago",
    note: "Refined recommendations and added source.",
    restorable: false,
  },
  {
    id: "v3",
    label: "v3",
    tag: "Approved",
    tagTone: "approved",
    who: "Dr. Rao",
    time: "Yesterday",
    note: "Approved for review cycle.",
    restorable: true,
  },
  {
    id: "v2",
    label: "v2",
    tag: "Human edited",
    tagTone: "human",
    who: "Dr. Rao",
    time: "2 days ago",
    note: "Edited tables and trend.",
    restorable: true,
  },
  {
    id: "v1",
    label: "v1",
    tag: "AI generated",
    tagTone: "ai",
    who: "Forevue",
    time: "3 days ago",
    note: "Initial draft generated from ERP records.",
    restorable: true,
  },
];

export const MOCK_COMMENTS: CommentEntry[] = [
  {
    id: "c1",
    initials: "KI",
    name: "K. Iyer",
    time: "2h ago",
    body: "Can we cite the attendance source in **Recommendations** before review?",
    avatarTone: "teal",
  },
  {
    id: "c2",
    initials: "DR",
    name: "Dr. Rao",
    time: "Yesterday",
    body: "Numbers look right. @A.Sharma please confirm Group C.",
    avatarTone: "deep",
  },
  {
    id: "c3",
    initials: "AS",
    name: "A. Sharma",
    time: "2 days ago",
    body: "Fixed the Group B figure.",
    resolved: true,
    avatarTone: "neutral",
  },
];

export const MOCK_METADATA: MetadataRow[] = [
  { id: "m1", icon: Hash, label: "Artifact ID", value: MOCK_ARTIFACT.id },
  { id: "m2", icon: User, label: "Owner", value: MOCK_ARTIFACT.owner },
  { id: "m3", icon: Sparkles, label: "Generated by", value: "Forevue AI" },
  { id: "m4", icon: Building2, label: "Department", value: MOCK_ARTIFACT.department },
  { id: "m5", icon: Building2, label: "Institution", value: "Northfield" },
  { id: "m6", icon: Calendar, label: "Academic year", value: "2025–26" },
  { id: "m7", icon: Info, label: "Version", value: MOCK_ARTIFACT.version },
  {
    id: "m8",
    icon: Globe,
    label: "Visibility",
    value: "Department",
    variant: "tag",
    tagColor: "var(--color-deep-teal)",
    tagBg: "var(--color-teal-50)",
  },
  {
    id: "m9",
    icon: Info,
    label: "Workflow stage",
    value: "Draft",
    variant: "tag",
    tagColor: "var(--color-neutral-600)",
    tagBg: "var(--color-neutral-100)",
  },
  {
    id: "m10",
    icon: Lock,
    label: "Data classification",
    value: MOCK_ARTIFACT.sensitivity,
    variant: "tag",
    tagColor: "var(--color-amber-700)",
    tagBg: "var(--color-amber-50)",
  },
];

export const MOCK_EXPORT_OPTIONS: ExportOption[] = [
  { id: "pdf", label: "PDF document", ext: "PDF", icon: FileText },
  { id: "docx", label: "Word document", ext: "DOCX", icon: FileText },
  { id: "xlsx", label: "Spreadsheet", ext: "XLSX", icon: FileSpreadsheet },
  { id: "csv", label: "CSV data", ext: "CSV", icon: FileSpreadsheet },
  { id: "print", label: "Print", ext: "", icon: Printer },
  { id: "link", label: "Share link", ext: "", icon: Link },
];

export const WORKFLOW_LABELS: Record<WorkflowStage, string> = {
  draft: "Draft",
  review: "Review",
  approved: "Approved",
  published: "Published",
};

export const MOCK_STATS = [
  { label: "On track", value: "83%", sub: "this period" },
  { label: "Need attention", value: "2", sub: "to review" },
  { label: "Trend", value: "+4", sub: "vs last period" },
];

export const MOCK_TABLE = {
  headers: ["Group", "In scope", "On track", "Trend"],
  rows: [
    ["Group A", "120", "92%", "Steady"],
    ["Group B", "96", "84%", "Up 2%"],
    ["Group C", "78", "71%", "Down 6%"],
  ],
};

export const MOCK_CHART_BARS = [
  { label: "P1", value: "78%", height: "69%" },
  { label: "P2", value: "74%", height: "65%" },
  { label: "P3", value: "81%", height: "71%" },
  { label: "P4", value: "69%", height: "61%", highlight: true },
  { label: "P5", value: "86%", height: "77%" },
];
