/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Db Roundtrip */
        get: operations["db_roundtrip_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mappings */
        get: operations["list_mappings_mappings_get"];
        put?: never;
        /**
         * Create Mapping
         * @description Mappings are saved and reused per source+entity (spec §5.3) — each
         *     POST adds a new version rather than overwriting, so a past import batch's
         *     mapping is always reconstructable.
         */
        post: operations["create_mapping_mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mappings/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest
         * @description Fuzzy header->canonical-field suggestion the user confirms before it's
         *     saved as a ColumnMapping (spec §5.3) — never auto-applied, so no DB write.
         */
        post: operations["suggest_mappings_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Import */
        post: operations["create_import_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{import_batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import */
        get: operations["get_import_imports__import_batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{import_batch_id}/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quarantine */
        get: operations["get_quarantine_imports__import_batch_id__quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Student 360
         * @description Unified record assembled across canonical tables (spec §5.9) — the
         *     proof-of-life read that the future Student Success Engine extends.
         */
        get: operations["get_student_360_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_risk_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/summary/by-department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary By Department */
        get: operations["get_summary_by_department_risk_summary_by_department_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List At Risk Students */
        get: operations["list_at_risk_students_risk_students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student Risk */
        get: operations["get_student_risk_risk_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_risk_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_risk_config_get"];
        /** Update Config */
        put: operations["update_config_risk_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interventions */
        get: operations["list_interventions_risk_interventions_get"];
        put?: never;
        /** Create Intervention */
        post: operations["create_intervention_risk_interventions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/interventions/{intervention_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Intervention */
        patch: operations["update_intervention_risk_interventions__intervention_id__patch"];
        trace?: never;
    };
    "/risk/interventions/{intervention_id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Outcome */
        post: operations["create_outcome_risk_interventions__intervention_id__outcome_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_risk_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/alerts/{alert_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Alert Read */
        patch: operations["mark_alert_read_risk_alerts__alert_id__read_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertResponse */
        AlertResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Assessment Id */
            assessment_id: string | null;
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /** Reason */
            reason: string;
            /** Payload */
            payload: Record<string, never>;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at: string | null;
        };
        /** AtRiskStudentResponse */
        AtRiskStudentResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Canonical Roll No */
            canonical_roll_no: string;
            /** Name */
            name: string;
            /** Tier */
            tier: string;
            /** Overall Score */
            overall_score: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /** AttendanceSummary */
        AttendanceSummary: {
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Total Sessions */
            total_sessions: number;
            /** Present Sessions */
            present_sessions: number;
            /** Percentage */
            percentage: number;
        };
        /** Body_create_import_imports_post */
        Body_create_import_imports_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
        };
        /** ColumnMappingCreate */
        ColumnMappingCreate: {
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
        };
        /** ColumnMappingResponse */
        ColumnMappingResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
            /** Version */
            version: number;
        };
        /** DepartmentSummary */
        DepartmentSummary: {
            /** Department */
            department: string;
            /** Total */
            total: number;
            /** High */
            high: number;
            /** Watch */
            watch: number;
            /** Low */
            low: number;
        };
        /** FeeSummary */
        FeeSummary: {
            /** Term */
            term: string;
            /** Fee Head */
            fee_head: string;
            /** Amount Due */
            amount_due: string | null;
            /** Amount Paid */
            amount_paid: string | null;
            /** Status */
            status: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportBatchResponse */
        ImportBatchResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
            /** Status */
            status: string;
            /** Row Count Raw */
            row_count_raw: number;
            /** Row Count Loaded */
            row_count_loaded: number;
            /** Row Count Quarantined */
            row_count_quarantined: number;
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Reconciliation Report */
            reconciliation_report: Record<string, never> | null;
            /** Risk Recompute Status */
            risk_recompute_status: string | null;
            /** Risk Recompute Summary */
            risk_recompute_summary: Record<string, never> | null;
        };
        /** InternalMarkSummary */
        InternalMarkSummary: {
            /** Course Id */
            course_id: string | null;
            /** Assessment Type */
            assessment_type: string;
            /** Attempt */
            attempt: number;
            /** Max Marks */
            max_marks: string;
            /** Obtained */
            obtained: string;
        };
        /** InterventionCreateRequest */
        InterventionCreateRequest: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Notes */
            notes?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Source Assessment Id */
            source_assessment_id?: string | null;
            /**
             * Guardian Consent Confirmed
             * @default false
             */
            guardian_consent_confirmed: boolean;
        };
        /** InterventionOutcomeCreateRequest */
        InterventionOutcomeCreateRequest: {
            /** Outcome */
            outcome: string;
            /** Notes */
            notes?: string | null;
        };
        /** InterventionOutcomeResponse */
        InterventionOutcomeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Intervention Id
             * Format: uuid
             */
            intervention_id: string;
            /** Outcome */
            outcome: string;
            /** Notes */
            notes: string | null;
            /** Recorded By */
            recorded_by: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** InterventionResponse */
        InterventionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Source Assessment Id */
            source_assessment_id: string | null;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Notes */
            notes: string | null;
            /** Assigned To */
            assigned_to: string | null;
            /** Created By */
            created_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** InterventionUpdateRequest */
        InterventionUpdateRequest: {
            /** Status */
            status?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Tenant Slug */
            tenant_slug: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MappingSuggestRequest */
        MappingSuggestRequest: {
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
            /** Headers */
            headers: string[];
        };
        /** MappingSuggestResponse */
        MappingSuggestResponse: {
            /** Suggestions */
            suggestions: {
                [key: string]: string | null;
            };
        };
        /** QuarantineRowResponse */
        QuarantineRowResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Cleaned Payload */
            cleaned_payload: Record<string, never>;
            /** Validation Errors */
            validation_errors: Record<string, never> | null;
        };
        /** RecomputeRequest */
        RecomputeRequest: {
            /** Scope */
            scope: string;
            /** Student Ids */
            student_ids?: string[] | null;
        };
        /** RecomputeSummaryResponse */
        RecomputeSummaryResponse: {
            /** Evaluated */
            evaluated: number;
            /** Changed */
            changed: number;
            /** Unchanged */
            unchanged: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors: Record<string, never>[];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Tenant Name */
            tenant_name: string;
            /** Tenant Slug */
            tenant_slug: string;
            /** Admin Email */
            admin_email: string;
            /** Admin Password */
            admin_password: string;
        };
        /** RiskAssessmentResponse */
        RiskAssessmentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Model Type */
            model_type: string;
            /** Model Version */
            model_version: string;
            /** Config Version */
            config_version: number;
            /** Overall Score */
            overall_score: number;
            /** Tier */
            tier: string;
            /** Subject Minor Status */
            subject_minor_status: string;
            /** Triggered By */
            triggered_by: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Findings */
            findings: components["schemas"]["RiskFindingResponse"][];
        };
        /**
         * RiskConfigModel
         * @description Validates the shape of risk_configs.config on PUT /risk/config (spec
         *     §6.1, Phase 2 hardening CHANGE 2) -- a malformed admin update must never
         *     reach set_new_config and poison every later recompute with a KeyError
         *     deep in scoring.
         */
        RiskConfigModel: {
            /** Attendance Threshold Pct */
            attendance_threshold_pct: number;
            /** Attendance Min Sessions */
            attendance_min_sessions: number;
            /** Attendance Trend Window */
            attendance_trend_window: number;
            /** Attendance Decline Points */
            attendance_decline_points: number;
            /** Academic Fail Pct */
            academic_fail_pct: number;
            /** Academic Decline Points */
            academic_decline_points: number;
            /** Fee Overdue Days */
            fee_overdue_days: number;
            weights: components["schemas"]["RiskWeights"];
            tier_cutoffs: components["schemas"]["TierCutoffs"];
        };
        /** RiskConfigResponse */
        RiskConfigResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /** Is Active */
            is_active: boolean;
            /** Config */
            config: Record<string, never>;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RiskConfigUpdateRequest */
        RiskConfigUpdateRequest: {
            config: components["schemas"]["RiskConfigModel"];
        };
        /** RiskFindingResponse */
        RiskFindingResponse: {
            /** Risk Type */
            risk_type: string;
            /** Code */
            code: string;
            /** Severity */
            severity: string;
            /** Weight Contribution */
            weight_contribution: number;
            /** Message */
            message: string;
            /** Evidence */
            evidence: Record<string, never>;
        };
        /** RiskSummaryByDepartmentResponse */
        RiskSummaryByDepartmentResponse: {
            /** Departments */
            departments: components["schemas"]["DepartmentSummary"][];
        };
        /** RiskSummaryByTier */
        RiskSummaryByTier: {
            /** High */
            high: number;
            /** Watch */
            watch: number;
            /** Low */
            low: number;
        };
        /** RiskSummaryByType */
        RiskSummaryByType: {
            /** Attendance */
            attendance: number;
            /** Academic */
            academic: number;
            /** Fee */
            fee: number;
        };
        /** RiskSummaryResponse */
        RiskSummaryResponse: {
            /** Total Assessed */
            total_assessed: number;
            by_tier: components["schemas"]["RiskSummaryByTier"];
            by_risk_type: components["schemas"]["RiskSummaryByType"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * RiskWeights
         * @description Mirrors DEFAULT_RISK_CONFIG["weights"] (spec §6.1). Coupled to rule-set
         *     v1's five codes -- when a future rule is added, this model must be
         *     updated alongside it (Phase 2 hardening CHANGE 2).
         */
        RiskWeights: {
            /** Attendance Below Threshold */
            ATTENDANCE_BELOW_THRESHOLD: number;
            /** Attendance Declining */
            ATTENDANCE_DECLINING: number;
            /** Academic Failing Internals */
            ACADEMIC_FAILING_INTERNALS: number;
            /** Academic Decline */
            ACADEMIC_DECLINE: number;
            /** Fee Overdue */
            FEE_OVERDUE: number;
        };
        /** SourceSystemCreate */
        SourceSystemCreate: {
            /** Name */
            name: string;
            /** Precedence */
            precedence: number;
        };
        /** SourceSystemResponse */
        SourceSystemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Precedence */
            precedence: number;
        };
        /** Student360Response */
        Student360Response: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Roll No */
            canonical_roll_no: string;
            /** Name */
            name: string;
            /** Dob */
            dob: string | null;
            /** Gender */
            gender: string | null;
            /** Category */
            category: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Admission Year */
            admission_year: number | null;
            /** Programme Id */
            programme_id: string | null;
            /** Status */
            status: string | null;
            /** Attendance Summary */
            attendance_summary: components["schemas"]["AttendanceSummary"][];
            /** Marks */
            marks: components["schemas"]["InternalMarkSummary"][];
            /** Fees */
            fees: components["schemas"]["FeeSummary"][];
        };
        /** StudentRiskDetailResponse */
        StudentRiskDetailResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            current: components["schemas"]["RiskAssessmentResponse"] | null;
            /** History */
            history: components["schemas"]["RiskAssessmentResponse"][];
            /** Active Interventions */
            active_interventions: components["schemas"]["InterventionResponse"][];
        };
        /** TierCutoffs */
        TierCutoffs: {
            /** Watch */
            watch: number;
            /** High */
            high: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    db_roundtrip_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSystemResponse"][];
                };
            };
        };
    };
    create_source_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceSystemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSystemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mappings_mappings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnMappingResponse"][];
                };
            };
        };
    };
    create_mapping_mappings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnMappingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnMappingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_mappings_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingSuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingSuggestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_import_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_import_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_imports__import_batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quarantine_imports__import_batch_id__quarantine_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineRowResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_360_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student360Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_risk_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSummaryResponse"];
                };
            };
        };
    };
    get_summary_by_department_risk_summary_by_department_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSummaryByDepartmentResponse"];
                };
            };
        };
    };
    list_at_risk_students_risk_students_get: {
        parameters: {
            query?: {
                tier?: string | null;
                risk_type?: string | null;
                department?: string | null;
                min_score?: number | null;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtRiskStudentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_risk_risk_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRiskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_risk_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecomputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_risk_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigResponse"];
                };
            };
        };
    };
    update_config_risk_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interventions_risk_interventions_get: {
        parameters: {
            query?: {
                student_id?: string | null;
                status?: string | null;
                assigned_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intervention_risk_interventions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_intervention_risk_interventions__intervention_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intervention_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_outcome_risk_interventions__intervention_id__outcome_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intervention_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionOutcomeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionOutcomeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_risk_alerts_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_alert_read_risk_alerts__alert_id__read_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
