/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Db Roundtrip */
        get: operations["db_roundtrip_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_users__user_id__patch"];
        trace?: never;
    };
    "/users/{user_id}/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Faculty Scopes */
        get: operations["list_faculty_scopes_users__user_id__scopes_get"];
        put?: never;
        /** Add Faculty Scope */
        post: operations["add_faculty_scope_users__user_id__scopes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/scopes/{scope_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Faculty Scope */
        delete: operations["remove_faculty_scope_users__user_id__scopes__scope_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mappings */
        get: operations["list_mappings_mappings_get"];
        put?: never;
        /**
         * Create Mapping
         * @description Mappings are saved and reused per source+entity (spec §5.3) — each
         *     POST adds a new version rather than overwriting, so a past import batch's
         *     mapping is always reconstructable.
         */
        post: operations["create_mapping_mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mappings/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest
         * @description Fuzzy header->canonical-field suggestion the user confirms before it's
         *     saved as a ColumnMapping (spec §5.3) — never auto-applied, so no DB write.
         */
        post: operations["suggest_mappings_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Import */
        post: operations["create_import_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{import_batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import */
        get: operations["get_import_imports__import_batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{import_batch_id}/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quarantine */
        get: operations["get_quarantine_imports__import_batch_id__quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student 360 */
        get: operations["get_student_360_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_students__student_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/timetable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timetable */
        get: operations["get_timetable_students__student_id__timetable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignments */
        get: operations["list_assignments_students__student_id__assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attendance */
        get: operations["get_attendance_students__student_id__attendance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/exam-prep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam Prep Route */
        get: operations["get_exam_prep_route_students__student_id__exam_prep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/career": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Career */
        get: operations["get_career_students__student_id__career_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_students__student_id__notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activity */
        get: operations["list_activity_students__student_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campus/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campus Announcements */
        get: operations["list_campus_announcements_campus_announcements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_risk_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/summary/by-department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary By Department */
        get: operations["get_summary_by_department_risk_summary_by_department_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List At Risk Students */
        get: operations["list_at_risk_students_risk_students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student Risk */
        get: operations["get_student_risk_risk_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_risk_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_risk_config_get"];
        /** Update Config */
        put: operations["update_config_risk_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interventions */
        get: operations["list_interventions_risk_interventions_get"];
        put?: never;
        /** Create Intervention */
        post: operations["create_intervention_risk_interventions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/interventions/{intervention_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Intervention */
        patch: operations["update_intervention_risk_interventions__intervention_id__patch"];
        trace?: never;
    };
    "/risk/interventions/{intervention_id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Outcome */
        post: operations["create_outcome_risk_interventions__intervention_id__outcome_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_risk_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/alerts/{alert_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Alert Read */
        patch: operations["mark_alert_read_risk_alerts__alert_id__read_patch"];
        trace?: never;
    };
    "/ai/semantic/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Semantic Schema */
        get: operations["get_semantic_schema_ai_semantic_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/semantic/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Semantic Query */
        post: operations["post_semantic_query_ai_semantic_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Index Document */
        post: operations["post_index_document_ai_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Ask */
        post: operations["post_ask_ai_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertResponse */
        AlertResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Assessment Id */
            assessment_id: string | null;
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /** Reason */
            reason: string;
            /** Payload */
            payload: Record<string, never>;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at: string | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Abstained */
            abstained: boolean;
            /** Interpretation */
            interpretation?: string | null;
            /** Metric */
            metric?: string | null;
            /** Columns */
            columns?: string[];
            /** Rows */
            rows?: Record<string, never>[];
            /** Narration */
            narration?: string | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Session Id */
            session_id: string;
            /** Evidence Sources */
            evidence_sources?: string[];
        };
        /** AssignmentResponse */
        AssignmentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Course Code */
            course_code?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Title */
            title: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Due Label */
            due_label: string;
            /** Status */
            status: string;
            /** Progress Pct */
            progress_pct: number;
            /** Priority */
            priority: string;
        };
        /** AssignmentsListResponse */
        AssignmentsListResponse: {
            /** Open Count */
            open_count: number;
            /** Items */
            items: components["schemas"]["AssignmentResponse"][];
        };
        /** AtRiskStudentResponse */
        AtRiskStudentResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Canonical Roll No */
            canonical_roll_no: string;
            /** Name */
            name: string;
            /** Tier */
            tier: string;
            /** Overall Score */
            overall_score: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /** AttendanceCourseDetail */
        AttendanceCourseDetail: {
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Course Code */
            course_code: string;
            /** Course Name */
            course_name: string;
            /** Percentage */
            percentage: number;
            /** Present Sessions */
            present_sessions: number;
            /** Total Sessions */
            total_sessions: number;
            /** Below Threshold */
            below_threshold: boolean;
        };
        /** AttendanceDetailResponse */
        AttendanceDetailResponse: {
            /** Overall Pct */
            overall_pct: number;
            /** Required Pct */
            required_pct: number;
            /** Predicted Pct */
            predicted_pct: number | null;
            /** Margin Sessions */
            margin_sessions: number | null;
            /** Note */
            note: string;
            /** Courses */
            courses: components["schemas"]["AttendanceCourseDetail"][];
        };
        /** AttendanceSummary */
        AttendanceSummary: {
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Course Code */
            course_code?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Total Sessions */
            total_sessions: number;
            /** Present Sessions */
            present_sessions: number;
            /** Percentage */
            percentage: number;
        };
        /** Body_create_import_imports_post */
        Body_create_import_imports_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
        };
        /** CampusAnnouncementResponse */
        CampusAnnouncementResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Body */
            body: string | null;
            /** Location */
            location: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Closes At */
            closes_at: string | null;
            /** Time Label */
            time_label: string;
        };
        /** CareerOpportunity */
        CareerOpportunity: {
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /**
             * Icon
             * @default briefcase
             */
            icon: string;
        };
        /** CareerProfileResponse */
        CareerProfileResponse: {
            /** Readiness Score */
            readiness_score: number;
            /** Skills */
            skills: string[];
            /** Opportunities */
            opportunities: components["schemas"]["CareerOpportunity"][];
            /** Credits Completed */
            credits_completed: number;
            /** Credits Required */
            credits_required: number;
            /** Narrative */
            narrative: string;
        };
        /** CoachItem */
        CoachItem: {
            /** Title */
            title: string;
            /** Why */
            why: string;
            /** Cta */
            cta: string;
            /** Coach Key */
            coach_key: string;
        };
        /** ColumnMappingCreate */
        ColumnMappingCreate: {
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
        };
        /** ColumnMappingResponse */
        ColumnMappingResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
            /** Version */
            version: number;
        };
        /** CourseRef */
        CourseRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** DailyBriefResponse */
        DailyBriefResponse: {
            /** Text */
            text: string;
            /** Bullets */
            bullets: string[];
        };
        /** DepartmentSummary */
        DepartmentSummary: {
            /** Department */
            department: string;
            /** Total */
            total: number;
            /** High */
            high: number;
            /** Watch */
            watch: number;
            /** Low */
            low: number;
        };
        /** ExamPrepResponse */
        ExamPrepResponse: {
            /** Overall Readiness */
            overall_readiness: number;
            /** Headline */
            headline: string;
            /** Tip */
            tip: string;
            /** Subjects */
            subjects: components["schemas"]["ExamSubjectReadiness"][];
        };
        /** ExamSubjectReadiness */
        ExamSubjectReadiness: {
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Course Code */
            course_code: string;
            /** Course Name */
            course_name: string;
            /** Readiness Pct */
            readiness_pct: number;
            /** Exam Name */
            exam_name?: string | null;
            /** Exam Date */
            exam_date?: string | null;
            /** Days Until Exam */
            days_until_exam?: number | null;
        };
        /** FacultyScopeCreateRequest */
        FacultyScopeCreateRequest: {
            /** Scope Type */
            scope_type: string;
            /** Scope Ref */
            scope_ref: string;
        };
        /** FacultyScopeResponse */
        FacultyScopeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Scope Type */
            scope_type: string;
            /** Scope Ref */
            scope_ref: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeeSummary */
        FeeSummary: {
            /** Term */
            term: string;
            /** Fee Head */
            fee_head: string;
            /** Amount Due */
            amount_due: string | null;
            /** Amount Paid */
            amount_paid: string | null;
            /** Status */
            status: string | null;
        };
        /** GovernedDocumentCreateRequest */
        GovernedDocumentCreateRequest: {
            /** Title */
            title: string;
            /** Source Label */
            source_label: string;
            /** Content */
            content: string;
        };
        /** GovernedDocumentCreateResponse */
        GovernedDocumentCreateResponse: {
            /** Document Id */
            document_id: string;
            /** Chunk Count */
            chunk_count: number;
        };
        /** GrowthStat */
        GrowthStat: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Icon */
            icon: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthFactor */
        HealthFactor: {
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Weight Pct */
            weight_pct: number;
        };
        /** ImportBatchResponse */
        ImportBatchResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
            /** Status */
            status: string;
            /** Row Count Raw */
            row_count_raw: number;
            /** Row Count Loaded */
            row_count_loaded: number;
            /** Row Count Quarantined */
            row_count_quarantined: number;
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Reconciliation Report */
            reconciliation_report: Record<string, never> | null;
            /** Risk Recompute Status */
            risk_recompute_status: string | null;
            /** Risk Recompute Summary */
            risk_recompute_summary: Record<string, never> | null;
        };
        /** InternalMarkSummary */
        InternalMarkSummary: {
            /** Course Id */
            course_id: string | null;
            /** Course Code */
            course_code?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Assessment Type */
            assessment_type: string;
            /** Attempt */
            attempt: number;
            /** Max Marks */
            max_marks: string;
            /** Obtained */
            obtained: string;
        };
        /** InterventionCreateRequest */
        InterventionCreateRequest: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Notes */
            notes?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Source Assessment Id */
            source_assessment_id?: string | null;
            /**
             * Guardian Consent Confirmed
             * @default false
             */
            guardian_consent_confirmed: boolean;
        };
        /** InterventionOutcomeCreateRequest */
        InterventionOutcomeCreateRequest: {
            /** Outcome */
            outcome: string;
            /** Notes */
            notes?: string | null;
        };
        /** InterventionOutcomeResponse */
        InterventionOutcomeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Intervention Id
             * Format: uuid
             */
            intervention_id: string;
            /** Outcome */
            outcome: string;
            /** Notes */
            notes: string | null;
            /** Recorded By */
            recorded_by: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** InterventionResponse */
        InterventionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Source Assessment Id */
            source_assessment_id: string | null;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Notes */
            notes: string | null;
            /** Assigned To */
            assigned_to: string | null;
            /** Created By */
            created_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** InterventionUpdateRequest */
        InterventionUpdateRequest: {
            /** Status */
            status?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** KpiItem */
        KpiItem: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Sub */
            sub?: string | null;
            /** Delta */
            delta?: string | null;
            /** Delta Dir */
            delta_dir?: string | null;
            /** Value Class */
            value_class?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Tenant Slug */
            tenant_slug: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** MappingSuggestRequest */
        MappingSuggestRequest: {
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Entity Type */
            entity_type: string;
            /** Headers */
            headers: string[];
        };
        /** MappingSuggestResponse */
        MappingSuggestResponse: {
            /** Suggestions */
            suggestions: {
                [key: string]: string | null;
            };
        };
        /** MeResponse */
        MeResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Student Id */
            student_id?: string | null;
        };
        /** QuarantineRowResponse */
        QuarantineRowResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Cleaned Payload */
            cleaned_payload: Record<string, never>;
            /** Validation Errors */
            validation_errors: Record<string, never> | null;
        };
        /** RecomputeRequest */
        RecomputeRequest: {
            /** Scope */
            scope: string;
            /** Student Ids */
            student_ids?: string[] | null;
        };
        /** RecomputeSummaryResponse */
        RecomputeSummaryResponse: {
            /** Evaluated */
            evaluated: number;
            /** Changed */
            changed: number;
            /** Unchanged */
            unchanged: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors: Record<string, never>[];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Tenant Name */
            tenant_name: string;
            /** Tenant Slug */
            tenant_slug: string;
            /** Admin Email */
            admin_email: string;
            /** Admin Password */
            admin_password: string;
        };
        /** RiskAssessmentResponse */
        RiskAssessmentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Model Type */
            model_type: string;
            /** Model Version */
            model_version: string;
            /** Config Version */
            config_version: number;
            /** Overall Score */
            overall_score: number;
            /** Tier */
            tier: string;
            /** Subject Minor Status */
            subject_minor_status: string;
            /** Triggered By */
            triggered_by: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Findings */
            findings: components["schemas"]["RiskFindingResponse"][];
        };
        /**
         * RiskConfigModel
         * @description Validates the shape of risk_configs.config on PUT /risk/config (spec
         *     §6.1, Phase 2 hardening CHANGE 2) -- a malformed admin update must never
         *     reach set_new_config and poison every later recompute with a KeyError
         *     deep in scoring.
         */
        RiskConfigModel: {
            /** Attendance Threshold Pct */
            attendance_threshold_pct: number;
            /** Attendance Min Sessions */
            attendance_min_sessions: number;
            /** Attendance Trend Window */
            attendance_trend_window: number;
            /** Attendance Decline Points */
            attendance_decline_points: number;
            /** Academic Fail Pct */
            academic_fail_pct: number;
            /** Academic Decline Points */
            academic_decline_points: number;
            /** Fee Overdue Days */
            fee_overdue_days: number;
            weights: components["schemas"]["RiskWeights"];
            tier_cutoffs: components["schemas"]["TierCutoffs"];
        };
        /** RiskConfigResponse */
        RiskConfigResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /** Is Active */
            is_active: boolean;
            /** Config */
            config: Record<string, never>;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RiskConfigUpdateRequest */
        RiskConfigUpdateRequest: {
            config: components["schemas"]["RiskConfigModel"];
        };
        /** RiskFindingResponse */
        RiskFindingResponse: {
            /** Risk Type */
            risk_type: string;
            /** Code */
            code: string;
            /** Severity */
            severity: string;
            /** Weight Contribution */
            weight_contribution: number;
            /** Message */
            message: string;
            /** Evidence */
            evidence: Record<string, never>;
        };
        /** RiskSummaryByDepartmentResponse */
        RiskSummaryByDepartmentResponse: {
            /** Departments */
            departments: components["schemas"]["DepartmentSummary"][];
        };
        /** RiskSummaryByTier */
        RiskSummaryByTier: {
            /** High */
            high: number;
            /** Watch */
            watch: number;
            /** Low */
            low: number;
        };
        /** RiskSummaryByType */
        RiskSummaryByType: {
            /** Attendance */
            attendance: number;
            /** Academic */
            academic: number;
            /** Fee */
            fee: number;
        };
        /** RiskSummaryResponse */
        RiskSummaryResponse: {
            /** Total Assessed */
            total_assessed: number;
            by_tier: components["schemas"]["RiskSummaryByTier"];
            by_risk_type: components["schemas"]["RiskSummaryByType"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * RiskWeights
         * @description Mirrors DEFAULT_RISK_CONFIG["weights"] (spec §6.1). Coupled to rule-set
         *     v1's five codes -- when a future rule is added, this model must be
         *     updated alongside it (Phase 2 hardening CHANGE 2).
         */
        RiskWeights: {
            /** Attendance Below Threshold */
            ATTENDANCE_BELOW_THRESHOLD: number;
            /** Attendance Declining */
            ATTENDANCE_DECLINING: number;
            /** Academic Failing Internals */
            ACADEMIC_FAILING_INTERNALS: number;
            /** Academic Decline */
            ACADEMIC_DECLINE: number;
            /** Fee Overdue */
            FEE_OVERDUE: number;
        };
        /** SemanticMetricSchema */
        SemanticMetricSchema: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Value Type */
            value_type: string;
            /** Allowed Dimensions */
            allowed_dimensions: string[];
            /** Allowed Filters */
            allowed_filters: string[];
        };
        /** SemanticQueryRequest */
        SemanticQueryRequest: {
            /** Metric */
            metric: string;
            /** Dimensions */
            dimensions?: string[];
            /** Filters */
            filters?: {
                [key: string]: string;
            };
            /**
             * Limit
             * @default 100
             */
            limit: number;
        };
        /** SemanticQueryResponse */
        SemanticQueryResponse: {
            /** Metric */
            metric: string;
            /** Columns */
            columns: string[];
            /** Rows */
            rows: Record<string, never>[];
            /** Row Count */
            row_count: number;
            /** Truncated */
            truncated: boolean;
            /** Interpretation */
            interpretation: string;
        };
        /** SemanticSchemaResponse */
        SemanticSchemaResponse: {
            /** Metrics */
            metrics: components["schemas"]["SemanticMetricSchema"][];
            /** Role */
            role: string;
        };
        /** SemesterTrendItem */
        SemesterTrendItem: {
            /** Label */
            label: string;
            /** Value Pct */
            value_pct: number;
        };
        /** SourceSystemCreate */
        SourceSystemCreate: {
            /** Name */
            name: string;
            /** Precedence */
            precedence: number;
        };
        /** SourceSystemResponse */
        SourceSystemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Precedence */
            precedence: number;
        };
        /** Student360Response */
        Student360Response: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Roll No */
            canonical_roll_no: string;
            /** Name */
            name: string;
            /** Dob */
            dob: string | null;
            /** Gender */
            gender: string | null;
            /** Category */
            category: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Admission Year */
            admission_year: number | null;
            /** Programme Id */
            programme_id: string | null;
            /** Programme Name */
            programme_name?: string | null;
            /** Status */
            status: string | null;
            /** Attendance Summary */
            attendance_summary: components["schemas"]["AttendanceSummary"][];
            /** Marks */
            marks: components["schemas"]["InternalMarkSummary"][];
            /** Fees */
            fees: components["schemas"]["FeeSummary"][];
            /** Course Lookup */
            course_lookup?: {
                [key: string]: components["schemas"]["CourseRef"];
            };
        };
        /** StudentActivityResponse */
        StudentActivityResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Activity Type */
            activity_type: string;
            /** Summary */
            summary: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Time Label */
            time_label: string;
        };
        /** StudentDashboardResponse */
        StudentDashboardResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Name */
            name: string;
            /** First Name */
            first_name: string;
            /** Programme Name */
            programme_name: string | null;
            /** Semester Label */
            semester_label: string;
            /** Session Label */
            session_label: string;
            /** Day Summary */
            day_summary: string;
            /** Health Score */
            health_score: number;
            /** Health Label */
            health_label: string;
            /** Health Factors */
            health_factors: components["schemas"]["HealthFactor"][];
            /** Health Narrative */
            health_narrative: string;
            /** Needs Attention */
            needs_attention: boolean;
            /** Attention Banner */
            attention_banner?: {
                [key: string]: string;
            } | null;
            /** Kpis */
            kpis: components["schemas"]["KpiItem"][];
            daily_brief: components["schemas"]["DailyBriefResponse"];
            /** Coach Items */
            coach_items: components["schemas"]["CoachItem"][];
            /** Growth Stats */
            growth_stats: components["schemas"]["GrowthStat"][];
            /** Semester Trend */
            semester_trend: components["schemas"]["SemesterTrendItem"][];
            /** Subject Health */
            subject_health: components["schemas"]["SubjectHealthItem"][];
            /** Cgpa */
            cgpa: number | null;
            /** Study Streak Days */
            study_streak_days: number;
            /** On Time Submissions */
            on_time_submissions: number;
        };
        /** StudentNotificationResponse */
        StudentNotificationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Body */
            body: string | null;
            /** Tone */
            tone: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read At */
            read_at: string | null;
            /** Time Label */
            time_label: string;
        };
        /** StudentRiskDetailResponse */
        StudentRiskDetailResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            current: components["schemas"]["RiskAssessmentResponse"] | null;
            /** History */
            history: components["schemas"]["RiskAssessmentResponse"][];
            /** Active Interventions */
            active_interventions: components["schemas"]["InterventionResponse"][];
        };
        /** SubjectHealthItem */
        SubjectHealthItem: {
            /** Course Code */
            course_code: string;
            /** Course Name */
            course_name: string;
            /** Status */
            status: string;
            /** Tier */
            tier: string;
        };
        /** TierCutoffs */
        TierCutoffs: {
            /** Watch */
            watch: number;
            /** High */
            high: number;
        };
        /** TimetableDayResponse */
        TimetableDayResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Summary */
            summary: string;
            /** Sessions */
            sessions: components["schemas"]["TimetableSessionResponse"][];
        };
        /** TimetableSessionResponse */
        TimetableSessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Course Id */
            course_id: string | null;
            /** Course Code */
            course_code?: string | null;
            /** Course Name */
            course_name?: string | null;
            /**
             * Session Date
             * Format: date
             */
            session_date: string;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /** End Time */
            end_time: string | null;
            /** Session Type */
            session_type: string;
            /** Title */
            title: string;
            /** Room */
            room: string | null;
            /** Faculty Name */
            faculty_name: string | null;
            /** Notes */
            notes: string | null;
            /** Status */
            status: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreateRequest */
        UserCreateRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Role */
            role: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserUpdateRequest */
        UserUpdateRequest: {
            /** Role */
            role?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    db_roundtrip_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_faculty_scopes_users__user_id__scopes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacultyScopeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_faculty_scope_users__user_id__scopes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacultyScopeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacultyScopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_faculty_scope_users__user_id__scopes__scope_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                scope_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSystemResponse"][];
                };
            };
        };
    };
    create_source_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceSystemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSystemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mappings_mappings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnMappingResponse"][];
                };
            };
        };
    };
    create_mapping_mappings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnMappingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnMappingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_mappings_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingSuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingSuggestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_import_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_import_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_imports__import_batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quarantine_imports__import_batch_id__quarantine_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineRowResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_360_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student360Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_students__student_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timetable_students__student_id__timetable_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimetableDayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assignments_students__student_id__assignments_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attendance_students__student_id__attendance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_prep_route_students__student_id__exam_prep_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamPrepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_career_students__student_id__career_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_students__student_id__notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentNotificationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activity_students__student_id__activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentActivityResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campus_announcements_campus_announcements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusAnnouncementResponse"][];
                };
            };
        };
    };
    get_summary_risk_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSummaryResponse"];
                };
            };
        };
    };
    get_summary_by_department_risk_summary_by_department_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSummaryByDepartmentResponse"];
                };
            };
        };
    };
    list_at_risk_students_risk_students_get: {
        parameters: {
            query?: {
                tier?: string | null;
                risk_type?: string | null;
                department?: string | null;
                min_score?: number | null;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtRiskStudentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_risk_risk_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRiskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_risk_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecomputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_risk_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigResponse"];
                };
            };
        };
    };
    update_config_risk_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interventions_risk_interventions_get: {
        parameters: {
            query?: {
                student_id?: string | null;
                status?: string | null;
                assigned_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intervention_risk_interventions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_intervention_risk_interventions__intervention_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intervention_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_outcome_risk_interventions__intervention_id__outcome_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intervention_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionOutcomeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionOutcomeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_risk_alerts_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_alert_read_risk_alerts__alert_id__read_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_semantic_schema_ai_semantic_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticSchemaResponse"];
                };
            };
        };
    };
    post_semantic_query_ai_semantic_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_index_document_ai_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GovernedDocumentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernedDocumentCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ask_ai_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
